
services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8080 --workers 4 wsgi:app
    ports:
      - "8080:8080"
    restart: always

  engine:
    build: .
    command: python main.py
    restart: always

  cornet-backend:
    build:
      context: ../corNet
    ports:
      - "7777:7777"
    restart: always

